name: go-memcache
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      memcached:
        image: memcached
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Tools
        run: make install-tools
      - name: Lint
        run: make lint
      - name: Test
        run: make test
